// <auto-generated />
using System;
using Competition.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Competition.Data.Migrations
{
    [DbContext(typeof(CompetitionDbContext))]
    [Migration("20260807095909_AddDisciplineSchedule")]
    partial class AddDisciplineSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Competition.Domain.CompetitionDiscipline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompetitionEditionId")
                        .HasColumnType("bigint");

                    b.Property<long>("DisciplineId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PlayingSystem")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("CompetitionEditionId", "DisciplineId")
                        .IsUnique();

                    b.HasIndex("CompetitionEditionId", "Order")
                        .IsUnique();

                    b.ToTable("CompetitionDisciplines", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompetitionDisciplines_Order", "\"Order\" > 0");

                            t.HasCheckConstraint("CK_CompetitionDisciplines_TeamSize", "TeamSize > 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.CompetitionEdition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("CreationToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreationToken")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CompetitionEditions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompetitionEditions_DateRange", "EndDate >= StartDate");
                        });
                });

            modelBuilder.Entity("Competition.Domain.CompetitionEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompetitionEditionId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompetitorId")
                        .HasColumnType("bigint");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorId");

                    b.HasIndex("CompetitionEditionId", "CompetitorId")
                        .IsUnique();

                    b.HasIndex("CompetitionEditionId", "Seed")
                        .IsUnique();

                    b.ToTable("CompetitionEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompetitionEntries_Seed", "Seed > 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.Competitor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Competitors");
                });

            modelBuilder.Entity("Competition.Domain.Discipline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Competition.Domain.DisciplinePhase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompetitionDisciplineId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PointsForDraw")
                        .HasColumnType("int");

                    b.Property<int>("PointsForLoss")
                        .HasColumnType("int");

                    b.Property<int>("PointsForWin")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionDisciplineId", "Order")
                        .IsUnique();

                    b.ToTable("DisciplinePhases", null, t =>
                        {
                            t.HasCheckConstraint("CK_DisciplinePhases_Order", "\"Order\" > 0");

                            t.HasCheckConstraint("CK_DisciplinePhases_Points", "PointsForWin >= 0 AND PointsForDraw >= 0 AND PointsForLoss >= 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.DisciplineStanding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompetitionDisciplineId")
                        .HasColumnType("bigint");

                    b.Property<long>("DisciplineTeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineTeamId");

                    b.HasIndex("CompetitionDisciplineId", "DisciplineTeamId")
                        .IsUnique();

                    b.HasIndex("CompetitionDisciplineId", "Rank");

                    b.ToTable("DisciplineStandings", null, t =>
                        {
                            t.HasCheckConstraint("CK_DisciplineStandings_Points", "PointsAwarded >= 0");

                            t.HasCheckConstraint("CK_DisciplineStandings_Rank", "Rank > 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.DisciplineTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompetitionDisciplineId")
                        .HasColumnType("bigint");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionDisciplineId", "Seed")
                        .IsUnique();

                    b.ToTable("DisciplineTeams", null, t =>
                        {
                            t.HasCheckConstraint("CK_DisciplineTeams_Seed", "Seed > 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.DisciplineTeamMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompetitionDisciplineId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompetitionEntryId")
                        .HasColumnType("bigint");

                    b.Property<long>("DisciplineTeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionEntryId");

                    b.HasIndex("CompetitionDisciplineId", "CompetitionEntryId")
                        .IsUnique();

                    b.HasIndex("CompetitionDisciplineId", "DisciplineTeamId");

                    b.HasIndex("DisciplineTeamId", "Order")
                        .IsUnique();

                    b.ToTable("DisciplineTeamMembers", null, t =>
                        {
                            t.HasCheckConstraint("CK_DisciplineTeamMembers_Order", "\"Order\" > 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.Match", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<long?>("AwayTeamId")
                        .HasColumnType("bigint");

                    b.Property<long>("DisciplinePhaseId")
                        .HasColumnType("bigint");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<long?>("HomeTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("PhaseGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("DisciplinePhaseId", "Order")
                        .IsUnique();

                    b.HasIndex("DisciplinePhaseId", "PhaseGroupId");

                    b.ToTable("Matches", null, t =>
                        {
                            t.HasCheckConstraint("CK_Matches_CompletedHasScore", "Status <> 'Completed' OR (HomeScore IS NOT NULL AND AwayScore IS NOT NULL)");

                            t.HasCheckConstraint("CK_Matches_DifferentTeams", "HomeTeamId IS NULL OR AwayTeamId IS NULL OR HomeTeamId <> AwayTeamId");

                            t.HasCheckConstraint("CK_Matches_Order", "\"Order\" > 0");

                            t.HasCheckConstraint("CK_Matches_Score", "(HomeScore IS NULL AND AwayScore IS NULL) OR (HomeScore >= 0 AND AwayScore >= 0)");
                        });
                });

            modelBuilder.Entity("Competition.Domain.MatchSetScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "SetNumber")
                        .IsUnique();

                    b.ToTable("MatchSetScores", null, t =>
                        {
                            t.HasCheckConstraint("CK_MatchSetScores_Score", "HomeScore >= 0 AND AwayScore >= 0");

                            t.HasCheckConstraint("CK_MatchSetScores_SetNumber", "SetNumber > 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.PhaseGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DisciplinePhaseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinePhaseId", "Name")
                        .IsUnique();

                    b.HasIndex("DisciplinePhaseId", "Order")
                        .IsUnique();

                    b.ToTable("PhaseGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhaseGroups_Order", "\"Order\" > 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.PhaseGroupTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DisciplinePhaseId")
                        .HasColumnType("bigint");

                    b.Property<long>("DisciplineTeamId")
                        .HasColumnType("bigint");

                    b.Property<long>("PhaseGroupId")
                        .HasColumnType("bigint");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineTeamId");

                    b.HasIndex("DisciplinePhaseId", "DisciplineTeamId")
                        .IsUnique();

                    b.HasIndex("DisciplinePhaseId", "PhaseGroupId");

                    b.HasIndex("PhaseGroupId", "Seed")
                        .IsUnique();

                    b.ToTable("PhaseGroupTeams", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhaseGroupTeams_Seed", "Seed > 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.RankingPointRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompetitionDisciplineId")
                        .HasColumnType("bigint");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionDisciplineId", "Rank")
                        .IsUnique();

                    b.ToTable("RankingPointRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_RankingPointRules_Points", "Points >= 0");

                            t.HasCheckConstraint("CK_RankingPointRules_Rank", "Rank > 0");
                        });
                });

            modelBuilder.Entity("Competition.Domain.CompetitionDiscipline", b =>
                {
                    b.HasOne("Competition.Domain.CompetitionEdition", "CompetitionEdition")
                        .WithMany("Disciplines")
                        .HasForeignKey("CompetitionEditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Competition.Domain.Discipline", "Discipline")
                        .WithMany("CompetitionDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionEdition");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("Competition.Domain.CompetitionEntry", b =>
                {
                    b.HasOne("Competition.Domain.CompetitionEdition", "CompetitionEdition")
                        .WithMany("Entries")
                        .HasForeignKey("CompetitionEditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Competition.Domain.Competitor", "Competitor")
                        .WithMany("CompetitionEntries")
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionEdition");

                    b.Navigation("Competitor");
                });

            modelBuilder.Entity("Competition.Domain.DisciplinePhase", b =>
                {
                    b.HasOne("Competition.Domain.CompetitionDiscipline", "CompetitionDiscipline")
                        .WithMany("Phases")
                        .HasForeignKey("CompetitionDisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionDiscipline");
                });

            modelBuilder.Entity("Competition.Domain.DisciplineStanding", b =>
                {
                    b.HasOne("Competition.Domain.CompetitionDiscipline", "CompetitionDiscipline")
                        .WithMany("FinalStandings")
                        .HasForeignKey("CompetitionDisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Competition.Domain.DisciplineTeam", "DisciplineTeam")
                        .WithMany("FinalStandingEntries")
                        .HasForeignKey("DisciplineTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionDiscipline");

                    b.Navigation("DisciplineTeam");
                });

            modelBuilder.Entity("Competition.Domain.DisciplineTeam", b =>
                {
                    b.HasOne("Competition.Domain.CompetitionDiscipline", "CompetitionDiscipline")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionDisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionDiscipline");
                });

            modelBuilder.Entity("Competition.Domain.DisciplineTeamMember", b =>
                {
                    b.HasOne("Competition.Domain.CompetitionEntry", "CompetitionEntry")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("CompetitionEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Competition.Domain.DisciplineTeam", "DisciplineTeam")
                        .WithMany("Members")
                        .HasForeignKey("CompetitionDisciplineId", "DisciplineTeamId")
                        .HasPrincipalKey("CompetitionDisciplineId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionEntry");

                    b.Navigation("DisciplineTeam");
                });

            modelBuilder.Entity("Competition.Domain.Match", b =>
                {
                    b.HasOne("Competition.Domain.DisciplineTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Competition.Domain.DisciplinePhase", "DisciplinePhase")
                        .WithMany("Matches")
                        .HasForeignKey("DisciplinePhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Competition.Domain.DisciplineTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Competition.Domain.PhaseGroup", "PhaseGroup")
                        .WithMany("Matches")
                        .HasForeignKey("DisciplinePhaseId", "PhaseGroupId")
                        .HasPrincipalKey("DisciplinePhaseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("DisciplinePhase");

                    b.Navigation("HomeTeam");

                    b.Navigation("PhaseGroup");
                });

            modelBuilder.Entity("Competition.Domain.MatchSetScore", b =>
                {
                    b.HasOne("Competition.Domain.Match", "Match")
                        .WithMany("SetScores")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Competition.Domain.PhaseGroup", b =>
                {
                    b.HasOne("Competition.Domain.DisciplinePhase", "DisciplinePhase")
                        .WithMany("Groups")
                        .HasForeignKey("DisciplinePhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DisciplinePhase");
                });

            modelBuilder.Entity("Competition.Domain.PhaseGroupTeam", b =>
                {
                    b.HasOne("Competition.Domain.DisciplineTeam", "DisciplineTeam")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("DisciplineTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Competition.Domain.PhaseGroup", "PhaseGroup")
                        .WithMany("Teams")
                        .HasForeignKey("DisciplinePhaseId", "PhaseGroupId")
                        .HasPrincipalKey("DisciplinePhaseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DisciplineTeam");

                    b.Navigation("PhaseGroup");
                });

            modelBuilder.Entity("Competition.Domain.RankingPointRule", b =>
                {
                    b.HasOne("Competition.Domain.CompetitionDiscipline", "CompetitionDiscipline")
                        .WithMany("RankingPointRules")
                        .HasForeignKey("CompetitionDisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionDiscipline");
                });

            modelBuilder.Entity("Competition.Domain.CompetitionDiscipline", b =>
                {
                    b.Navigation("FinalStandings");

                    b.Navigation("Phases");

                    b.Navigation("RankingPointRules");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Competition.Domain.CompetitionEdition", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Competition.Domain.CompetitionEntry", b =>
                {
                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("Competition.Domain.Competitor", b =>
                {
                    b.Navigation("CompetitionEntries");
                });

            modelBuilder.Entity("Competition.Domain.Discipline", b =>
                {
                    b.Navigation("CompetitionDisciplines");
                });

            modelBuilder.Entity("Competition.Domain.DisciplinePhase", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Competition.Domain.DisciplineTeam", b =>
                {
                    b.Navigation("FinalStandingEntries");

                    b.Navigation("GroupAssignments");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Competition.Domain.Match", b =>
                {
                    b.Navigation("SetScores");
                });

            modelBuilder.Entity("Competition.Domain.PhaseGroup", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
